# NeoForge mod metadata
modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

# Require NeoForge and Minecraft
[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
version="${neoforge_version}"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
version="${minecraft_version}"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[languages]]
name="java"
version="[17,)"
